export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const INCREMENT_ITEM_COUNT_CART = "INCREMENT_ITEM_COUNT_CART";
export const DECREMENT_ITEM_COUNT_CART = "DECREMENT_ITEM_COUNT_CART";
export const CLEAR_CART = "CLEAR_CART";
